### ISSUE TITLE
about F

### ISSUE THREAD

**Issue by wozaimoyu** [wuminghui123/D3L-HB#1]
F_real = (torch.matmul(RF_real,BB_real)-torch.matmul(RF_imag,BB_imag)).reshape(Nc,-1,K*Nt)
 F_imag = (torch.matmul(RF_imag,BB_real)+torch.matmul(RF_imag,BB_real)).reshape(Nc,-1,K*Nt)
may be
F_real = (torch.matmul(RF_real, BB_real) - torch.matmul(RF_imag, BB_imag)).reshape(Nc, -1, K * Nt)
 F_imag = (torch.matmul(RF_imag, BB_real) + torch.matmul(RF_real, BB_imag)).reshape(Nc, -1, K * Nt)
Or maybe I understand it wrong

**Comment by wuminghui123** [comment]
Thanks for your correction, we have modified the code accordingly. After simulation verification, the revised numerical results are basically unchanged.

**Comment by wuminghui123** [comment]
> F_real = (torch.matmul(RF_real,BB_real)-torch.matmul(RF_imag,BB_imag)).reshape(Nc,-1,K _Nt) F_imag = (torch.matmul(RF_imag,BB_real)+torch.matmul(RF_imag, BB_real)).reshape(Nc,-1,K_ Nt) 可能是 F_real = (torch.matmul(RF_real, BB_real) - torch.matmul(RF_imag, BB_imag)).reshape(Nc, -1, K * Nt) F_imag = (torch.matmul(RF_imag, BB_real) + torch.matmul(RF_real, BB_imag)).reshape(Nc, -1, K * Nt) 或者我理解错了

感谢您的更正，我们已相应地修改了代码。经过仿真验证，修正后的数值结果基本不变。
